let message = 'Coding is great';
console.log(message);
let studentCount = 0;
console.log(studentCount);
message = 'Coding maybe not be easy, but still great';
console.log(message);
studentCount = 16;
console.log(studentCount);
console.log(message.toLowerCase());
studentCount += 1;
console.log(studentCount);
confirm('You look beautiful, today');
let name = prompt('Hi! Your name, please.');
confirm('Hi! ' + name);
let firstName = prompt('Enter your first name: ');
let lastName = prompt('Enter your last name: ');
confirm('Hi! ' + firstName + lastName);
let dimensionSquare = prompt('Enter side length of the square: ');
confirm('The square of area: ' + dimension ** 2);
let radius = prompt('Enter the radius of the circle: ');
confirm('The circle area is: ' + radius * 3.14);
let degreeC = prompt('Enter the temperature in Celsius: ');
confirm(degreeC + '(C) = ' + (degreeC * 1.8) + 32);
alert("Well done!");